// Mocks generated by Mockito 5.4.5 from annotations
// in calorie_lens_ai_app/test/feat/calorie_lens_ai/presentation/cubits/onboarding_wizard/onboarding_wizard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:calorie_lens_ai_app/core/error/failure.dart' as _i6;
import 'package:calorie_lens_ai_app/core/usecases/usecases.dart' as _i8;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/entities/onboarding_wizard/user_profile_entity.dart'
    as _i7;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/repositories/onboarding_wizard/onboarding_wizard_repository.dart'
    as _i2;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/usecases/onboarding_wizard/calculate_and_save_nutrition_data.dart'
    as _i10;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/usecases/onboarding_wizard/check_onboarding_wizard_status.dart'
    as _i11;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/usecases/onboarding_wizard/complete_onboarding_wizard.dart'
    as _i12;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/usecases/onboarding_wizard/get_user_profile.dart'
    as _i4;
import 'package:calorie_lens_ai_app/feat/calorie_lens_ai/domain/usecases/onboarding_wizard/save_user_profile.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOnboardingWizardRepository_0 extends _i1.SmartFake
    implements _i2.OnboardingWizardRepository {
  _FakeOnboardingWizardRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfile extends _i1.Mock implements _i4.GetUserProfile {
  MockGetUserProfile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OnboardingWizardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOnboardingWizardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OnboardingWizardRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserProfileEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>);
}

/// A class which mocks [SaveUserProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveUserProfile extends _i1.Mock implements _i9.SaveUserProfile {
  MockSaveUserProfile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OnboardingWizardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOnboardingWizardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OnboardingWizardRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i7.UserProfileEntity? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [profile],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [profile],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [CalculateAndSaveNutritionData].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateAndSaveNutritionData extends _i1.Mock
    implements _i10.CalculateAndSaveNutritionData {
  MockCalculateAndSaveNutritionData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OnboardingWizardRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeOnboardingWizardRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.OnboardingWizardRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i7.UserProfileEntity? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [profile],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [profile],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [CheckOnboardingWizardStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckOnboardingWizardStatus extends _i1.Mock
    implements _i11.CheckOnboardingWizardStatus {
  MockCheckOnboardingWizardStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [CompleteOnboardingWizard].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteOnboardingWizard extends _i1.Mock
    implements _i12.CompleteOnboardingWizard {
  MockCompleteOnboardingWizard() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
